### ISSUE TITLE
Can't install to Visual Studio 2019

### ISSUE THREAD

**Issue by ghost** [GrzegorzKozub/VisualStudioExtensions#7]
```
31-May-19 18:27:03 - Microsoft VSIX Installer
31-May-19 18:27:03 - -------------------------------------------
31-May-19 18:27:03 - vsixinstaller.exe version:
31-May-19 18:27:03 - 16.1.3121
31-May-19 18:27:03 - -------------------------------------------
31-May-19 18:27:03 - Command line parameters:
31-May-19 18:27:03 - C:\Program Files (x86)\Microsoft Visual Studio\Installer\resources\app\ServiceHub\Services\Microsoft.VisualStudio.Setup.Service\VSIXInstaller.exe,C:\Users\Ihor\Downloads\TotalCommanderLauncher.vsix
31-May-19 18:27:03 - -------------------------------------------
31-May-19 18:27:03 - Microsoft VSIX Installer
31-May-19 18:27:03 - -------------------------------------------
31-May-19 18:27:03 - Initializing Install...
31-May-19 18:27:04 - Extension Details...
31-May-19 18:27:04 - 	Identifier         : 504f9f56-9629-48c7-adb9-cbcce53bf9b7
31-May-19 18:27:04 - 	Name               : Total Commander Launcher
31-May-19 18:27:04 - 	Author             : Grzegorz Kozub
31-May-19 18:27:04 - 	Version            : 1.5.0.0
31-May-19 18:27:04 - 	Description        : A command to launch Total Commander in the currently selected Solution Explorer item context. Added to the Tools and Solution Explorer menu when a solution or project is open.
31-May-19 18:27:04 - 	Locale             : en-US
31-May-19 18:27:04 - 	MoreInfoURL        : http://www.ghisler.com/
31-May-19 18:27:04 - 	InstalledByMSI     : False
31-May-19 18:27:04 - 	SupportedFrameworkVersionRange : [4.5]
31-May-19 18:27:04 - 
31-May-19 18:27:04 - 	SignatureState     : Unsigned
31-May-19 18:27:04 - 	Supported Products : 
31-May-19 18:27:04 - 		Microsoft.VisualStudio.Pro
31-May-19 18:27:04 - 			Version : [11.0,16.0]
31-May-19 18:27:04 - 		Microsoft.VisualStudio.Premium
31-May-19 18:27:04 - 			Version : [11.0,16.0]
31-May-19 18:27:04 - 		Microsoft.VisualStudio.Ultimate
31-May-19 18:27:04 - 			Version : [11.0,16.0]
31-May-19 18:27:04 - 
31-May-19 18:27:04 - 	References         : 
31-May-19 18:27:04 - 		-------------------------------------------------------
31-May-19 18:27:04 - 		Identifier   : Microsoft.VisualStudio.MPF.11.0
31-May-19 18:27:04 - 		Name         : Visual Studio MPF 11.0
31-May-19 18:27:04 - 		Version      : [11.0]
31-May-19 18:27:04 - 		MoreInfoURL  : 
31-May-19 18:27:04 - 		Nested       : No
31-May-19 18:27:04 - 
31-May-19 18:27:04 - 	Prerequisites      : 
31-May-19 18:27:04 - 		-------------------------------------------------------
31-May-19 18:27:04 - 		Identifier   : Microsoft.VisualStudio.Component.CoreEditor
31-May-19 18:27:04 - 		Name         : Visual Studio core editor
31-May-19 18:27:04 - 		Version      : [15.0.26208.0,)
31-May-19 18:27:04 - 
31-May-19 18:27:04 - Signature Details...
31-May-19 18:27:04 - 	Extension is not signed.
31-May-19 18:27:04 - 
31-May-19 18:27:04 - Searching for applicable products...
31-May-19 18:27:04 - Found installed product - Global Location
31-May-19 18:27:04 - Found installed product - Visual Studio Community 2019
31-May-19 18:27:04 - VSIXInstaller.NoApplicableSKUsException: This extension is not installable on any currently installed products.
   at VSIXInstaller.ExtensionService.GetInstallableData(String vsixPath, String extensionPackParentName, Boolean isRepairSupported, IStateData stateData, IEnumerable`1& skuData)
   at VSIXInstaller.ExtensionPackService.IsExtensionPack(IStateData stateData, Boolean isRepairSupported)
   at VSIXInstaller.ExtensionPackService.ExpandExtensionPackToInstall(IStateData stateData, Boolean isRepairSupported)
   at VSIXInstaller.App.Initialize(Boolean isRepairSupported)
   at VSIXInstaller.App.Initialize()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)

```

**Comment by GrzegorzKozub** [comment]
Fixed by d7376b61e442ec56efde3b8dd1a34a7683267d2f. Sorry for that!
